title: SBGN
project_name: SBGN
description: >
  Systems Biology Graphical Notation
repository_url: https://github.com/sbgn
repository_shorthand: sbgn/Something

baseurl: "/sbgn"

author_name: sbgn
author_url: https://github.com/sbgn

markdown: kramdown

gems:
  - jekyll-sitemap
